name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  intl: ^0.19.0
  provider: ^6.1.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
